# Compose used for production

version: '3.5'

services:
  versoes_props:
    build:
      context: ./
      dockerfile: ./Dockerfile
      cache_from:
        - agoradigital/versoes_props
    image: agoradigital/versoes_props
    container_name: versoes_props
    volumes:
      - leggo_data:/versoes_props/data
      - leggo_content_data:/versoes_props/leggo_content_data

volumes:
  leggo_data:
    external:
      name: leggo_data
  leggo_content_data:
    name: leggo_content_data
